### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [dk949/searocket#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by dk949** [comment]
Hi, thanks for reaching out.

I have a license file,  it can be found [here](https://github.com/dk949/searocket/blob/trunk/LICENSE).

**Comment by unixorn** [comment]
Thanks. Could you please add a screen shot?

**Comment by dk949** [comment]
> Thanks. Could you please add a screen shot?

Sure, I'm doing a big refractor at the moment, once that's finilised I'll add a usage GIF and update the docs.

Could you also let me know how you came across this repo? Thanks.

**Comment by unixorn** [comment]
I use GitHub's earch to look for new zsh plugins and themes every day or two to keep the list updated, then order the results by recently updated.

**Comment by unixorn** [comment]
Once you're done with the refactor, you can either close this ticket and/or file a PR against [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), whichever is more convenient for you.

**Comment by dk949** [comment]
Hi, added screenshot and docs (couldn't get a GIF unfortunately).

**Comment by unixorn** [comment]
pngs are fine, I don't think there are any reasonably recent browsers that can't display them.
